### ISSUE TITLE
Cancel Appointments

### ISSUE THREAD

**Issue by nmo-dev** [athenahealth/apiserver-athenaFlex#194] opened 2021-07-29 17:25 UTC
I can successfully cancel appointments in CPS via the API. However, I'm encountering a fatal error when trying to cancel appointments with one of our custom appointment statuses:
Appointment status can not be updated. current Appointment status : [Web Portal In Progress]

I can cancel the appointment when I change the status to "Scheduled" before hand via the API. I can also change the appointment status to "Web Portal In Progress" without issue. This seems a little clunky to do and was hoping to just outright cancel the appointment, instead of implementing a workaround. I'm unsure what I'm missing to successfully cancel an appointment in all use cases. Hope this made sense.

I have checked and made sure that these appointment statuses are in our mappings.properties file.

EDIT: In addition, when cancelling the appointment, CPS does not release the appt slot table properly but will still cancel the appointment in the appointments table. This causes an issue with using that slot. When trying to schedule a new appointment, this will cause an overbook instead of putting it in the actual slot. Not sure if the the two problems are related but figure I'd put this in here.

**Comment by nmo-dev** [comment] 2021-08-24 16:08
@Torin-Shepard-athena Sorry to directly ping but I haven't heard anything regarding this issue in almost a month. My main concern is the releasing of appointment slots when cancelling via the API. Is there something I'm missing? The appointment will cancel, however, if someone tries to schedule in a slot that was canceled via API it will overbook the appointment because the system thinks that the slot is still occupied.

This is when I try to cancel within my production environment.

**Comment by bjalbert-athena** [comment] 2022-02-09 20:10
HI, 
Sorry for the delay in the answer.  I hope this is still needed.  

As for the issue with appointment slots not being released and causing and overbooked appointment when cancelled via FHIR API.  This is a known bug and is fixed in v22 and beyond.

We can use custom appointment statuses, but they ultimately they have to map to one of those 7 statues that are outlined in the API resource documentation.  These are mapped in the mappings.properties file located below as you mentioned.  Please note there are multiple mappings.properties files so be sure you modify the on it the directory below.

C:\Program Files\Centricity Practice Solution\jboss\standalone\deployments\(db Name)APIServer.war\WEB-INF\classes\com\gehcit\fhir\mappers\util

Open this location in NotePad++ as administrator.  Then search for the following:

#Used to map CPS APPTOINTMENT.STATUS to FHIR Appointment Status Codes

This will take you to the section in the file you will need to make the mods.  It looks like below.

#Used to map CPS APPTOINTMENT.STATUS to FHIR Appointment Status Codes
APPOINTMENTSTATUS_CPS.Arrived=arrived|[http://hl7.org/fhir/appointmentstatus|Arrived](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CArrived__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evT_chLsN$)
APPOINTMENTSTATUS_CPS.Scheduled=booked|[http://hl7.org/fhir/appointmentstatus|Booked](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CBooked__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evWmzReLp$)
APPOINTMENTSTATUS_CPS.No\ Show =noshow|[http://hl7.org/fhir/appointmentstatus|No](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CNo__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7eve_Oxrdz$) Show
APPOINTMENTSTATUS_CPS.Completed=fulfilled|[http://hl7.org/fhir/appointmentstatus|Fulfilled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CFulfilled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evVHa9-LJ$)
APPOINTMENTSTATUS_CPS.Default=pending|[http://hl7.org/fhir/appointmentstatus|Pending](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CPending__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evdS33tQP$)
APPOINTMENTSTATUS_CPS.proposed=proposed|[http://hl7.org/fhir/appointmentstatus|Proposed](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CProposed__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evacH8okE$)
APPOINTMENTSTATUS_CPS.Canceled\ by\ Patient=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Cancel/Patient=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Cancel/Doctor=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Operator\ Error=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Cancel\ Less\ than\ 24hrs=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Deceased=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Answered-Confirmed=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)
APPOINTMENTSTATUS_CPS.Barry\ Test=cancelled|[http://hl7.org/fhir/appointmentstatus|Cancelled](https://urldefense.com/v3/__http:/hl7.org/fhir/appointmentstatus*7CCancelled__;JQ!!E3l7wfIP!woyPJ49iBAEu-tjNn5YNjlgxufYkLndMvKr_OwBUrcOMBu3DwpMdWN7evYZiELx_$)

Notice the last line.  I added a custom appointment status called Barry Test and mapped it to cancelled.  You will want to keep this same syntax.  Just change to whatever API status you want to map to.  Also notice the "\" after Barry above.  The "\" has to go before any space in the name.

Once you make the change save and then run Jconsole to redeploy the (DB Name)APIServer.war file.

I hope this helps,
-Barry

**Comment by AjeetYadav07** [comment] 2022-09-20 06:15
Marking this issue as closed. if you have any issue, please raise a new ticket.

**Closed by AjeetYadav07** 2022-09-20 06:15 UTC
